name: Run Scrapper

on:
  workflow_dispatch: # 允許手動點擊執行

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev libssl-dev

      - name: Compile C++ Scrapper
        run: |
          g++ -O3 *.cpp src/*.cpp -Iinclude -lcurl -lcrypto -o eset_scraper

      - name: Run Scrapper
        run: |
          ./eset_scraper
