name: Run Scrapper

on:
  workflow_dispatch: # 允許手動點擊執行

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # 修正：這裡改成正確的 docker 官方套件

      - name: Build and Run Scrapper
        run: |
          docker build . -t esetkeysscrapper:latest
          docker run --rm esetkeysscrapper:latest
